# Generated by Django 5.1.5 on 2025-02-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_film_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='rating',
        ),
        migrations.AddField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(through='core.FilmGenre', to='core.genre'),
        ),
        migrations.AddField(
            model_name='rating',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
