# Generated by Django 5.1.5 on 2025-02-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_film_rating_film_genres_rating_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
