# Generated by Django 5.1.5 on 2025-02-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_film_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='video_url',
        ),
        migrations.AddField(
            model_name='film',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='films/videos/'),
        ),
    ]
