# Generated by Django 5.1.5 on 2025-02-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_rating_user_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
    ]
